package com.revature.petapp.data;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

import java.util.ArrayList;
import java.util.List;
import com.revature.petapp.models.Pet;
import com.revature.petapp.models.Species;
import com.revature.petapp.models.Status;
import com.revature.petapp.models.User;
import com.revature.petapp.utils.ConnectionUtil;

public class UserPostgres implements UserDAO {
	private ConnectionUtil connUtil = ConnectionUtil.getConnectionUtil();

	@Override
	public User create(User user) throws SQLException {
		try (Connection conn = connUtil.getConnection()) {
			// because this is a transaction (DML), we'll start by
			// setting autocommit to false
			conn.setAutoCommit(false);

			String sql = "insert into person " + "(id, username, passwd) " + "values (default, ?, ?)";
			// when inserting, we want to retrieve the ID that was generated
			// so we need to specify which column(s) are autogenerated
			String[] keys = { "id" };

			PreparedStatement stmt = conn.prepareStatement(sql, keys);
			stmt.setString(1, user.getUsername());
			stmt.setString(2, user.getPassword());

			int rowsAffected = stmt.executeUpdate();
			ResultSet resultSet = stmt.getGeneratedKeys();
			if (resultSet.next() && rowsAffected == 1) {
				user.setId(resultSet.getInt("id"));
				if (addPetsToUser(user, conn)) {
					conn.commit();
				} else {
					conn.rollback();
				}
			} else {
				conn.rollback();
				return null;
			}

		} catch (SQLException e) {
			if (e.getMessage().contains("unique constraint")) {
				throw e;
			}
			e.printStackTrace();
		}

		return user;
	}

	@Override
	public User findById(int id) {
		User user = null;

		// try-with-resources: sets up closing for closeable resources
		try (Connection conn = connUtil.getConnection()) {
			// set up the SQL statement that we want to execute
			String sql = "select id, username, passwd from person where id=?";

			// set up that statement with the database
			// preparedstatement is pre-processed to prevent sql injection
			PreparedStatement stmt = conn.prepareStatement(sql);
			stmt.setInt(1, id); // parameter indexes start at 1 (the first ?)

			// execute the statement
			ResultSet resultSet = stmt.executeQuery();

			// process the result set
			if (resultSet.next()) {
				user = new User();
				user.setId(id);
				user.setUsername(resultSet.getString("username"));
				user.setPassword(resultSet.getString("passwd"));
				user.setPets(this.getPetsByUser(user, conn));
			}

		} catch (SQLException e) {
			e.printStackTrace();
		}

		return user;
	}

	@Override
	public List<User> findAll() {
		List<User> users = new ArrayList<>();
		// try-with-resources: sets up closing for closeable resources
		try (Connection conn = connUtil.getConnection()) {
			// set up the SQL statement that we want to execute
			String sql = "select id, username, passwd from person";

			// set up that statement with the database
			// preparedstatement is pre-processed to prevent sql injection
			PreparedStatement stmt = conn.prepareStatement(sql);

			// execute the statement
			ResultSet resultSet = stmt.executeQuery();

			// process the result set
			while (resultSet.next()) {
				User user = new User();
				user.setId(resultSet.getInt("id"));
				user.setUsername(resultSet.getString("username"));
				user.setPassword(resultSet.getString("passwd"));
				user.setPets(this.getPetsByUser(user, conn));
				users.add(user);
			}

		} catch (SQLException e) {
			e.printStackTrace();
		}
		return users;
	}

	@Override
	public void update(User t) {
		// TODO Auto-generated method stub

	}

	@Override
	public void delete(User t) {
		// TODO Auto-generated method stub

	}

	@Override
	public User findByUsername(String username) {
		User user = null;

		// try-with-resources: sets up closing for closeable resources
		try (Connection conn = connUtil.getConnection()) {
			// set up the SQL statement that we want to execute
			String sql = "select id, username, passwd from person where username=?";

			// set up that statement with the database
			// preparedstatement is pre-processed to prevent sql injection
			PreparedStatement stmt = conn.prepareStatement(sql);
			stmt.setString(1, username); // parameter indexes start at 1 (the first ?)

			// execute the statement
			ResultSet resultSet = stmt.executeQuery();

			// process the result set
			if (resultSet.next()) {
				user = new User();
				user.setId(resultSet.getInt("id"));
				user.setUsername(resultSet.getString("username"));
				user.setPassword(resultSet.getString("passwd"));
				user.setPets(this.getPetsByUser(user, conn));
			}

		} catch (SQLException e) {
			//e.printStackTrace();
		}

		return user;
	}
	
	private List<Pet> getPetsByUser(User user, Connection conn) throws SQLException {
		List<Pet> pets = new ArrayList<>();
		
		String sql = "select pet.id, " 
				+ "pet.name, " 
				+ "age, " 
				+ "pet.description, "
				+ "status.id as status_id, "
				+ "status.name as status_name, "
				+ "species.id as species_id, " 
				+ "species.name as species_name, "
				+ "species.description as species_description " 
				+ "from pet "
				+ "join species on pet.species_id = species.id " 
				+ "join status on pet.status_id = status.id "
				+ "where owner_id=?";
		PreparedStatement stmt = conn.prepareStatement(sql);
		stmt.setInt(1, user.getId());
		ResultSet resultSet = stmt.executeQuery();
		
		while (resultSet.next()) {
			Pet pet = new Pet();
			String name = resultSet.getString("name");
			int age = resultSet.getInt("age");
			String description = resultSet.getString("description");
			
			Status status = new Status(resultSet.getInt("status_id"),
					resultSet.getString("status_name"));
			
			Species species = new Species(
					resultSet.getInt("species_id"),
					resultSet.getString("species_name"),
					resultSet.getString("species_description"));

			pet = new Pet(name, age, species, description);
			pet.setId(resultSet.getInt("id"));
			pet.setStatus(status);
			
			pets.add(pet);
		}
		
		return pets;
	}
	
	/**
	 * 
	 * @param user
	 * @param conn
	 * @return true if successful, false if transaction should be rolled back
	 * @throws SQLException
	 */
	private boolean addPetsToUser(User user, Connection conn) throws SQLException {
		String sql = "select id from pet where owner_id=?";
		PreparedStatement stmt = conn.prepareStatement(sql);
		stmt.setInt(1, user.getId());
		
		ResultSet resultSet = stmt.executeQuery();
		List<Integer> existingIds = new ArrayList<>();
		while (resultSet.next()) {
			existingIds.add(resultSet.getInt("id"));
		}
		
		for (Pet pet : user.getPets()) {
			if (existingIds.contains(pet.getId())) {
				sql = "update pet set owner_id=? where id=?";
				stmt = conn.prepareStatement(sql);
				stmt.setInt(1, user.getId());
				stmt.setInt(2, pet.getId());
				
				int rowsUpdated = stmt.executeUpdate();
				if (rowsUpdated!=1) {
					return false;
				}
			}
		}
		return true;
	}

}
